experiment:
  project_name: "SynthRLProject"
  group: "observer"
  run_name: "try_original_settings_again"

training:
  batch_size: 64
  epochs: 15
  val_fraction: 0.1
  num_samples: 500000

observer:
  learning_rate: 1e-4
  feature_dim: 128

data:
  # Relative to the location of train_observer.py
  directory: "../data/labeled_spectrograms"
  tfrecord_filename: "SimpleSynth_original.tfrecords"

model_saving:
  # Relative to the location of train_observer.py
  base_dir: "../saved_models/observer"
