experiment:
  project_name: "SynthRLProject"
  group: "end_to_end"
  run_name: "base_cutoff_adsr_simple_reward"

environment:
  sampling_rate: 44100.0
  note_length: 0.5
  control_mode: "incremental"
  render_mode: false

agent:
  hidden_dim: 256
  gamma: 0.9
  tau: 0.005
  policy_noise: 0.2
  noise_clip: 0.5
  policy_delay: 2

replay_buffer:
  capacity: 100000
  batch_size: 128

training:
  num_episodes: 3000
  trainable_observer: false

model_loading:
  load_observer_weights: true
  # This is the subfolder name you want to load from (if any)
  observer_subfolder: "20250203_1642_first_try_cutoff_adsr"

  load_pretrained_agent: false
  # This is the subfolder name you want to load from (if any)
  agent_subfolder: "20250120_1901_spectrogram_only_state"

  # Optionally load just the actor weights (from pretrain_actor.py)
  load_actor_weights: false
  actor_subfolder: "20250205_2012_pretrain_actor_cutoff_adsr"

model_saving:
  base_dir: "../saved_models/end_to_end"
