experiment:
  project_name: "SynthRLProject"
  group: "agent"
  run_name: "spectrogram_only_state"

environment:
  sampling_rate: 44100.0
  note_length: 0.5
  control_mode: "incremental"
  render_mode: false

agent:
  hidden_dim: 256
  gamma: 0.9
  tau: 0.005
  policy_noise: 0.2
  noise_clip: 0.5
  policy_delay: 2

replay_buffer:
  capacity: 100000
  batch_size: 128

training:
  num_episodes: 2000
  trainable_observer: false

model_loading:
  load_observer_weights: true
  # This is the subfolder name you want to load from (if any)
  observer_subfolder: "20250106_2043_try_original_settings_again"

  load_pretrained_agent: false
  # This is the subfolder name you want to load from (if any)
  agent_subfolder: "20250101_120000_agent_training"

model_saving:
  base_dir: "../saved_models/agent"
