import numpy as np


def generate_saw(freq, t, amp=1.0):
    # Generate a sawtooth waveform.
    # A normalized saw wave can be generated by:
    # saw(t) = 2 * (t*freq - floor(t*freq)) - 1
    # This gives a waveform ranging from -1 to 1. We then scale it by 'amp'.
    waveform = 2 * (freq * t - np.floor(freq * t)) - 1.0
    return amp * waveform
